#!/usr/bin/env python3
"""Generate src/meta_db.c from tools/dump_neo.py output.

Usage:
    tools/gen_meta.py known_good_dump.tsv [more.tsv ...] > src/meta_db.c
or:
    tools/gen_meta.py known_good_dump.tsv -o src/meta_db.c

Input lines: filename \t year \t genre \t screenshot \t ngh \t name \t manu
(the header line is skipped).  The set name is the dump filename without
its .neo extension and must match a MAME set name; unknown names are
reported to stderr and skipped.  Later files override earlier ones, so a
correction file can be appended after the main dump.
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

def known_sets():
    db = (ROOT / "src/games_db.c").read_text()
    body = db.split("const nc_game nc_games[] = {", 1)[1]
    return set(re.findall(r'^\t\{ "([a-z0-9_]+)", ', body, re.M))

def main():
    args = sys.argv[1:]
    out = None
    if "-o" in args:
        i = args.index("-o")
        out = args[i + 1]
        del args[i:i + 2]
    if not args:
        print(__doc__.strip(), file=sys.stderr)
        return 2

    sets = known_sets()
    meta = {}
    for path in args:
        for line in open(path):
            line = line.rstrip("\n")
            if not line or line.startswith("filename\t"):
                continue
            f = line.split("\t")
            if len(f) < 7:
                print("bad line skipped: %r" % line, file=sys.stderr)
                continue
            name = f[0]
            if name.lower().endswith(".neo"):
                name = name[:-4]
            name = name.lower()
            if name not in sets:
                print("unknown set skipped: %s" % name, file=sys.stderr)
                continue
            title, manu = f[5][:33], f[6][:17]
            sizes = tuple(int(x, 16) for x in f[7:13]) if len(f) >= 13 \
                else (0, 0, 0, 0, 0, 0)
            meta[name] = (int(f[1]), int(f[2]), int(f[3]), int(f[4], 16),
                          title, manu, sizes)

    lines = []
    lines.append("/* SPDX-License-Identifier: BSD-3-Clause\n"
                 " * Generated by tools/gen_meta.py from a known-good .neo set\n"
                 " * dump (tools/dump_neo.py).  Do not edit by hand.\n"
                 " */\n"
                 "#include \"neoconv_internal.h\"\n\n"
                 "const nc_meta nc_metas[] = {\n")
    def esc(t):
        return t.replace("\\", "\\\\").replace('"', '\\"')
    for name in sorted(meta):
        year, genre, shot, ngh, title, manu, sz = meta[name]
        lines.append('\t{ "%s", %u, %u, %u, 0x%x, "%s", "%s",'
                     ' { 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x } },\n'
                     % ((name, year, genre, shot, ngh, esc(title), esc(manu))
                        + sz))
    lines.append("};\n\nconst size_t nc_num_metas = "
                 "sizeof(nc_metas) / sizeof(nc_metas[0]);\n")
    text = "".join(lines)

    if out:
        open(out, "w").write(text)
        print("wrote %s (%d sets)" % (out, len(meta)), file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0

if __name__ == "__main__":
    sys.exit(main())
